// <auto-generated />
using System;
using ItMarathon.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItMarathon.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240803224731_SeedAdditionalPropertyData")]
    partial class SeedAdditionalPropertyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ItMarathon.Dal.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomValue")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("PredefinedValueId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProposalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RequestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomValue");

                    b.HasIndex("PredefinedValueId");

                    b.HasIndex("PropertyDefinitionId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("RequestId");

                    b.ToTable("Properties", t =>
                        {
                            t.HasCheckConstraint("CK_Property_ProposalId_RequestId", "ProposalId IS NOT NULL OR RequestId IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PropertyDefinitionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PropertiesDefinition");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7075),
                            IsMandatory = true,
                            Name = "Вид тварини",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7122),
                            IsMandatory = true,
                            Name = "Порода",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7124),
                            IsMandatory = true,
                            Name = "Стать",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7126),
                            IsMandatory = true,
                            Name = "Вік",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7128),
                            IsMandatory = true,
                            Name = "Забарвлення",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7130),
                            IsMandatory = true,
                            Name = "Стерилізація",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7132),
                            IsMandatory = true,
                            Name = "Вакцинація",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7134),
                            IsMandatory = false,
                            Name = "Чіп",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7136),
                            IsMandatory = false,
                            Name = "Обробка від паразитів",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7138),
                            IsMandatory = false,
                            Name = "Ветпаспорт",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7140),
                            IsMandatory = false,
                            Name = "Родовід",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7142),
                            IsMandatory = false,
                            Name = "FCI/KCY",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(7144),
                            IsMandatory = false,
                            Name = "Щеняча метрика",
                            PropertyDefinitionType = 0
                        });
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PropertyDefinitionId");

                    b.HasIndex("Value");

                    b.ToTable("PropertyValues");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8750),
                            PropertyDefinitionId = 1L,
                            Value = "Собаки"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8763),
                            PropertyDefinitionId = 1L,
                            Value = "Коти"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8765),
                            PropertyDefinitionId = 1L,
                            Value = "Гризуни"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8767),
                            PropertyDefinitionId = 1L,
                            Value = "Риби"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8769),
                            PropertyDefinitionId = 1L,
                            Value = "Птахи"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8771),
                            PropertyDefinitionId = 1L,
                            Value = "Рептилії"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8773),
                            PropertyDefinitionId = 1L,
                            Value = "Інші"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8799),
                            PropertyDefinitionId = 3L,
                            Value = "Хлопчик"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8802),
                            PropertyDefinitionId = 3L,
                            Value = "Дівчинка"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8804),
                            PropertyDefinitionId = 5L,
                            Value = "Руде"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8806),
                            PropertyDefinitionId = 5L,
                            Value = "Біле"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8807),
                            PropertyDefinitionId = 5L,
                            Value = "Чорне"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8810),
                            PropertyDefinitionId = 5L,
                            Value = "Сіре"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8811),
                            PropertyDefinitionId = 5L,
                            Value = "Коричневе"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8813),
                            PropertyDefinitionId = 5L,
                            Value = "Кремове"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8815),
                            PropertyDefinitionId = 5L,
                            Value = "Палеве"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8817),
                            PropertyDefinitionId = 5L,
                            Value = "Рудувато-коричневе"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8819),
                            PropertyDefinitionId = 5L,
                            Value = "Золотисте"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8821),
                            PropertyDefinitionId = 5L,
                            Value = "Срібне"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8823),
                            PropertyDefinitionId = 5L,
                            Value = "Блакитне"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8825),
                            PropertyDefinitionId = 5L,
                            Value = "Зелене"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8827),
                            PropertyDefinitionId = 5L,
                            Value = "Жовте"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8829),
                            PropertyDefinitionId = 5L,
                            Value = "Оранжеве"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8831),
                            PropertyDefinitionId = 5L,
                            Value = "Рожеве"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8833),
                            PropertyDefinitionId = 5L,
                            Value = "Фіолетове"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8835),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Німецька вівчарка"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8839),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Лабрадор-ретрівер"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8841),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Йоркширський тер'єр"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8843),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Мопс"
                        },
                        new
                        {
                            Id = 30L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8845),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Золотистий ретрівер"
                        },
                        new
                        {
                            Id = 31L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8847),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Французький бульдог"
                        },
                        new
                        {
                            Id = 32L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8850),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Бігль"
                        },
                        new
                        {
                            Id = 33L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8852),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Чихуахуа"
                        },
                        new
                        {
                            Id = 34L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8854),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Такса"
                        },
                        new
                        {
                            Id = 35L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8856),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Сибірський хаскі"
                        },
                        new
                        {
                            Id = 36L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8858),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Американський стаффордширський тер'єр"
                        },
                        new
                        {
                            Id = 37L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8860),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Кокер-спанієль"
                        },
                        new
                        {
                            Id = 38L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8862),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Джек-рассел-тер'єр"
                        },
                        new
                        {
                            Id = 39L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8864),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Ши-тцу"
                        },
                        new
                        {
                            Id = 40L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8866),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Вест-хайленд-уайт-тер'єр"
                        },
                        new
                        {
                            Id = 41L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8869),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Мальтійська болонка"
                        },
                        new
                        {
                            Id = 42L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8871),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Боксер"
                        },
                        new
                        {
                            Id = 43L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8873),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Доберман"
                        },
                        new
                        {
                            Id = 44L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8875),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Шарпей"
                        },
                        new
                        {
                            Id = 45L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8877),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Акіта-іну"
                        },
                        new
                        {
                            Id = 46L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8879),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Британська короткошерста"
                        },
                        new
                        {
                            Id = 47L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8881),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Шотландська висловуха"
                        },
                        new
                        {
                            Id = 48L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8883),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Мейн-кун"
                        },
                        new
                        {
                            Id = 49L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8885),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Сфінкс"
                        },
                        new
                        {
                            Id = 50L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8888),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Перська"
                        },
                        new
                        {
                            Id = 51L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8890),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Сіамська"
                        },
                        new
                        {
                            Id = 52L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8892),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Європейська короткошерста"
                        },
                        new
                        {
                            Id = 53L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8894),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Бенгальська"
                        },
                        new
                        {
                            Id = 54L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8896),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Регдолл"
                        },
                        new
                        {
                            Id = 55L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8898),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Турецька ангора"
                        },
                        new
                        {
                            Id = 56L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8900),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Американська короткошерста"
                        },
                        new
                        {
                            Id = 57L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8902),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Невська маскарадна"
                        },
                        new
                        {
                            Id = 58L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8904),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Норвезька лісова"
                        },
                        new
                        {
                            Id = 59L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8906),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Сомалійська"
                        },
                        new
                        {
                            Id = 60L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8908),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Абіссинська"
                        },
                        new
                        {
                            Id = 61L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8911),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Орієнтальна"
                        },
                        new
                        {
                            Id = 62L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8913),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Екзотична короткошерста"
                        },
                        new
                        {
                            Id = 63L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8915),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Девон-рекс"
                        },
                        new
                        {
                            Id = 64L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8917),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Саванна"
                        },
                        new
                        {
                            Id = 65L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8919),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Бомбейська"
                        },
                        new
                        {
                            Id = 66L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8921),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Тонкінська"
                        },
                        new
                        {
                            Id = 67L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8923),
                            PropertyDefinitionId = 6L,
                            Value = "Так"
                        },
                        new
                        {
                            Id = 68L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8925),
                            PropertyDefinitionId = 6L,
                            Value = "Ні"
                        },
                        new
                        {
                            Id = 69L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8927),
                            PropertyDefinitionId = 7L,
                            Value = "Так"
                        },
                        new
                        {
                            Id = 70L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8929),
                            PropertyDefinitionId = 7L,
                            Value = "Ні"
                        },
                        new
                        {
                            Id = 71L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8931),
                            PropertyDefinitionId = 8L,
                            Value = "Так"
                        },
                        new
                        {
                            Id = 72L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8933),
                            PropertyDefinitionId = 8L,
                            Value = "Ні"
                        },
                        new
                        {
                            Id = 73L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8935),
                            PropertyDefinitionId = 9L,
                            Value = "Так"
                        },
                        new
                        {
                            Id = 74L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8937),
                            PropertyDefinitionId = 9L,
                            Value = "Ні"
                        },
                        new
                        {
                            Id = 75L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8938),
                            PropertyDefinitionId = 10L,
                            Value = "Так"
                        },
                        new
                        {
                            Id = 76L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8940),
                            PropertyDefinitionId = 10L,
                            Value = "Ні"
                        },
                        new
                        {
                            Id = 77L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8942),
                            PropertyDefinitionId = 11L,
                            Value = "Так"
                        },
                        new
                        {
                            Id = 78L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8944),
                            PropertyDefinitionId = 11L,
                            Value = "Ні"
                        },
                        new
                        {
                            Id = 79L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8946),
                            PropertyDefinitionId = 12L,
                            Value = "Так"
                        },
                        new
                        {
                            Id = 80L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8948),
                            PropertyDefinitionId = 12L,
                            Value = "Ні"
                        },
                        new
                        {
                            Id = 81L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8950),
                            PropertyDefinitionId = 13L,
                            Value = "Так"
                        },
                        new
                        {
                            Id = 82L,
                            CreatedOn = new DateTime(2024, 8, 4, 1, 47, 31, 192, DateTimeKind.Local).AddTicks(8952),
                            PropertyDefinitionId = 13L,
                            Value = "Ні"
                        });
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Proposal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AppUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PetOrigin")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("Location");

                    b.HasIndex("Price");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.ProposalPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ProposalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.ToTable("ProposalsPhoto");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AppUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Property", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.PropertyValue", "PredefinedValue")
                        .WithOne("Property")
                        .HasForeignKey("ItMarathon.Dal.Entities.Property", "PredefinedValueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItMarathon.Dal.Entities.PropertyDefinition", "PropertyDefinition")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItMarathon.Dal.Entities.Proposal", "Proposal")
                        .WithMany("Properties")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ItMarathon.Dal.Entities.Request", "Request")
                        .WithMany("Properties")
                        .HasForeignKey("RequestId");

                    b.Navigation("PredefinedValue");

                    b.Navigation("PropertyDefinition");

                    b.Navigation("Proposal");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyValue", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.PropertyValue", "ParentPropertyValue")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItMarathon.Dal.Entities.PropertyDefinition", "PropertyDefinition")
                        .WithMany("PropertyValues")
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentPropertyValue");

                    b.Navigation("PropertyDefinition");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Proposal", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.AppUser", "AppUser")
                        .WithMany("Proposals")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.ProposalPhoto", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.Proposal", "Proposal")
                        .WithMany("Photos")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Request", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.AppUser", "AppUser")
                        .WithMany("Requests")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.AppUser", b =>
                {
                    b.Navigation("Proposals");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyDefinition", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("PropertyValues");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyValue", b =>
                {
                    b.Navigation("Property");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Proposal", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Request", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
