// <auto-generated />
using System;
using ItMarathon.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItMarathon.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ItMarathon.Dal.Entities.AccessToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(43)
                        .HasColumnType("varchar(43)")
                        .HasColumnName("token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Token");

                    b.HasIndex(new[] { "UserId" }, "fk_access_tokens_user_id_users");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_access_tokens_created_at");

                    b.ToTable("access_tokens");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSuperuser")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_superuser");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_verified");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PrefersPhoneCall")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("prefers_phone_call");

                    b.Property<bool>("PrefersTelegram")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("prefers_telegram");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "ix_users_email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomValue")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("PredefinedValueId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProposalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RequestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomValue");

                    b.HasIndex("PredefinedValueId");

                    b.HasIndex("PropertyDefinitionId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("RequestId");

                    b.ToTable("Properties", t =>
                        {
                            t.HasCheckConstraint("CK_Property_ProposalId_RequestId", "ProposalId IS NOT NULL OR RequestId IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PropertyDefinitionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PropertiesDefinition");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = true,
                            Name = "Вид тварини",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = true,
                            Name = "Різновид",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = true,
                            Name = "Стать",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "Забарвлення",
                            PropertyDefinitionType = 0
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Health",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "Стерилізація",
                            PropertyDefinitionType = 1
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Health",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "Вакцинація",
                            PropertyDefinitionType = 1
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Health",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "Чіп",
                            PropertyDefinitionType = 1
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Health",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "Обробка від паразитів",
                            PropertyDefinitionType = 1
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Documents",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "Ветпаспорт",
                            PropertyDefinitionType = 1
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Documents",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "Родовід",
                            PropertyDefinitionType = 1
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Documents",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "FCI/KCY",
                            PropertyDefinitionType = 1
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Documents",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMandatory = false,
                            Name = "Щеняча метрика",
                            PropertyDefinitionType = 1
                        });
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PropertyDefinitionId");

                    b.HasIndex("Value");

                    b.ToTable("PropertyValues");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 1L,
                            Value = "Собаки"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 1L,
                            Value = "Коти"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 1L,
                            Value = "Гризуни"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 1L,
                            Value = "Риби"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 1L,
                            Value = "Птахи"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 1L,
                            Value = "Рептилії"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 1L,
                            Value = "Інші"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 3L,
                            Value = "Хлопчик"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 3L,
                            Value = "Дівчинка"
                        },
                        new
                        {
                            Id = 154L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            PropertyDefinitionId = 3L,
                            Value = "Невідомо"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Руде"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Біле"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Чорне"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Сіре"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Коричневе"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Кремове"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Палеве"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Рудувато-коричневе"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Золотисте"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Срібне"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Блакитне"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Зелене"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Жовте"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Оранжеве"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Рожеве"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyDefinitionId = 5L,
                            Value = "Фіолетове"
                        },
                        new
                        {
                            Id = 155L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            PropertyDefinitionId = 5L,
                            Value = "Інше"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Німецька вівчарка"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Лабрадор-ретрівер"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Йоркширський тер'єр"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Мопс"
                        },
                        new
                        {
                            Id = 30L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Золотистий ретрівер"
                        },
                        new
                        {
                            Id = 31L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Французький бульдог"
                        },
                        new
                        {
                            Id = 32L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Бігль"
                        },
                        new
                        {
                            Id = 33L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Чихуахуа"
                        },
                        new
                        {
                            Id = 34L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Такса"
                        },
                        new
                        {
                            Id = 35L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Сибірський хаскі"
                        },
                        new
                        {
                            Id = 36L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Американський стаффордширський тер'єр"
                        },
                        new
                        {
                            Id = 37L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Кокер-спанієль"
                        },
                        new
                        {
                            Id = 38L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Джек-рассел-тер'єр"
                        },
                        new
                        {
                            Id = 39L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Ши-тцу"
                        },
                        new
                        {
                            Id = 40L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Вест-хайленд-уайт-тер'єр"
                        },
                        new
                        {
                            Id = 41L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Мальтійська болонка"
                        },
                        new
                        {
                            Id = 42L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Боксер"
                        },
                        new
                        {
                            Id = 43L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Доберман"
                        },
                        new
                        {
                            Id = 44L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Шарпей"
                        },
                        new
                        {
                            Id = 45L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Акіта-іну"
                        },
                        new
                        {
                            Id = 156L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 1L,
                            PropertyDefinitionId = 2L,
                            Value = "Інше"
                        },
                        new
                        {
                            Id = 46L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Британська короткошерста"
                        },
                        new
                        {
                            Id = 47L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Шотландська висловуха"
                        },
                        new
                        {
                            Id = 48L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Мейн-кун"
                        },
                        new
                        {
                            Id = 49L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Сфінкс"
                        },
                        new
                        {
                            Id = 50L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Перська"
                        },
                        new
                        {
                            Id = 51L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Сіамська"
                        },
                        new
                        {
                            Id = 52L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Європейська короткошерста"
                        },
                        new
                        {
                            Id = 53L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Бенгальська"
                        },
                        new
                        {
                            Id = 54L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Регдолл"
                        },
                        new
                        {
                            Id = 55L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Турецька ангора"
                        },
                        new
                        {
                            Id = 56L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Американська короткошерста"
                        },
                        new
                        {
                            Id = 57L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Невська маскарадна"
                        },
                        new
                        {
                            Id = 58L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Норвезька лісова"
                        },
                        new
                        {
                            Id = 59L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Сомалійська"
                        },
                        new
                        {
                            Id = 60L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Абіссинська"
                        },
                        new
                        {
                            Id = 61L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Орієнтальна"
                        },
                        new
                        {
                            Id = 62L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Екзотична короткошерста"
                        },
                        new
                        {
                            Id = 63L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Девон-рекс"
                        },
                        new
                        {
                            Id = 64L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Саванна"
                        },
                        new
                        {
                            Id = 65L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Бомбейська"
                        },
                        new
                        {
                            Id = 66L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Тонкінська"
                        },
                        new
                        {
                            Id = 157L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 2L,
                            PropertyDefinitionId = 2L,
                            Value = "Інше"
                        },
                        new
                        {
                            Id = 83L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Хом'як"
                        },
                        new
                        {
                            Id = 84L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Миша"
                        },
                        new
                        {
                            Id = 85L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Морська свинка"
                        },
                        new
                        {
                            Id = 86L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Шиншила"
                        },
                        new
                        {
                            Id = 87L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Щур"
                        },
                        new
                        {
                            Id = 88L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Кролик"
                        },
                        new
                        {
                            Id = 89L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Заєць"
                        },
                        new
                        {
                            Id = 90L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Капібара"
                        },
                        new
                        {
                            Id = 91L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Песець"
                        },
                        new
                        {
                            Id = 92L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Білка"
                        },
                        new
                        {
                            Id = 158L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 3L,
                            PropertyDefinitionId = 2L,
                            Value = "Інше"
                        },
                        new
                        {
                            Id = 93L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Золота рибка"
                        },
                        new
                        {
                            Id = 94L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Гупі"
                        },
                        new
                        {
                            Id = 95L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Тернеція"
                        },
                        new
                        {
                            Id = 96L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Скалярія"
                        },
                        new
                        {
                            Id = 97L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Молінезія"
                        },
                        new
                        {
                            Id = 98L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Сом-панда"
                        },
                        new
                        {
                            Id = 99L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Барбус"
                        },
                        new
                        {
                            Id = 100L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Ампулярія"
                        },
                        new
                        {
                            Id = 101L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Коридорас"
                        },
                        new
                        {
                            Id = 102L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Торакатум"
                        },
                        new
                        {
                            Id = 103L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Пецилія"
                        },
                        new
                        {
                            Id = 104L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Тетра"
                        },
                        new
                        {
                            Id = 105L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Неон"
                        },
                        new
                        {
                            Id = 106L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Мечоносець"
                        },
                        new
                        {
                            Id = 107L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Лабео"
                        },
                        new
                        {
                            Id = 108L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Рамірезі"
                        },
                        new
                        {
                            Id = 109L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Даніо"
                        },
                        new
                        {
                            Id = 110L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Морський коник"
                        },
                        new
                        {
                            Id = 159L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 4L,
                            PropertyDefinitionId = 2L,
                            Value = "Інше"
                        },
                        new
                        {
                            Id = 111L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Хвилястий папуга"
                        },
                        new
                        {
                            Id = 112L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Корелла"
                        },
                        new
                        {
                            Id = 113L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Жако"
                        },
                        new
                        {
                            Id = 114L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Какаду"
                        },
                        new
                        {
                            Id = 115L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Амадін"
                        },
                        new
                        {
                            Id = 116L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Нерозлучники"
                        },
                        new
                        {
                            Id = 117L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Ара"
                        },
                        new
                        {
                            Id = 118L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Лорікет"
                        },
                        new
                        {
                            Id = 119L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Канарка"
                        },
                        new
                        {
                            Id = 120L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Голуб"
                        },
                        new
                        {
                            Id = 121L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Павлін"
                        },
                        new
                        {
                            Id = 122L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Фазан"
                        },
                        new
                        {
                            Id = 123L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Індик"
                        },
                        new
                        {
                            Id = 124L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Перепілка"
                        },
                        new
                        {
                            Id = 125L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Качка"
                        },
                        new
                        {
                            Id = 126L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Гуска"
                        },
                        new
                        {
                            Id = 127L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Півень"
                        },
                        new
                        {
                            Id = 128L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Курка"
                        },
                        new
                        {
                            Id = 129L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Пелікан"
                        },
                        new
                        {
                            Id = 130L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Страус"
                        },
                        new
                        {
                            Id = 160L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 5L,
                            PropertyDefinitionId = 2L,
                            Value = "Інше"
                        },
                        new
                        {
                            Id = 131L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Ящірка"
                        },
                        new
                        {
                            Id = 132L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Гекон"
                        },
                        new
                        {
                            Id = 133L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Ігуана"
                        },
                        new
                        {
                            Id = 134L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Змія"
                        },
                        new
                        {
                            Id = 135L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Сухопутна черепаха"
                        },
                        new
                        {
                            Id = 136L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Морська черепаха"
                        },
                        new
                        {
                            Id = 137L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Водна черепаха"
                        },
                        new
                        {
                            Id = 138L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Хамелеон"
                        },
                        new
                        {
                            Id = 161L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 6L,
                            PropertyDefinitionId = 2L,
                            Value = "Інше"
                        },
                        new
                        {
                            Id = 139L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Тритон"
                        },
                        new
                        {
                            Id = 140L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Павук"
                        },
                        new
                        {
                            Id = 141L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Лемур"
                        },
                        new
                        {
                            Id = 142L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Скорпіон"
                        },
                        new
                        {
                            Id = 143L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Саламандра"
                        },
                        new
                        {
                            Id = 144L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Єнот"
                        },
                        new
                        {
                            Id = 145L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Альпака"
                        },
                        new
                        {
                            Id = 146L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Кінь"
                        },
                        new
                        {
                            Id = 147L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Лама"
                        },
                        new
                        {
                            Id = 148L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Дикобраз"
                        },
                        new
                        {
                            Id = 149L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Їжак"
                        },
                        new
                        {
                            Id = 150L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Осел"
                        },
                        new
                        {
                            Id = 151L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Коза"
                        },
                        new
                        {
                            Id = 152L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Корова"
                        },
                        new
                        {
                            Id = 153L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Свиня"
                        },
                        new
                        {
                            Id = 162L,
                            CreatedOn = new DateTime(2024, 8, 16, 17, 4, 10, 300, DateTimeKind.Utc),
                            ParentId = 7L,
                            PropertyDefinitionId = 2L,
                            Value = "Інше"
                        });
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Proposal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AgeUnits")
                        .HasColumnType("int");

                    b.Property<long>("AppUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PetName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PetOrigin")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("Location");

                    b.HasIndex("Price");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.ProposalPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ProposalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.ToTable("ProposalsPhoto");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AppUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.AccessToken", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.AppUser", "User")
                        .WithMany("AccessTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_tokens_user_id_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Property", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.PropertyValue", "PredefinedValue")
                        .WithOne("Property")
                        .HasForeignKey("ItMarathon.Dal.Entities.Property", "PredefinedValueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItMarathon.Dal.Entities.PropertyDefinition", "PropertyDefinition")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItMarathon.Dal.Entities.Proposal", "Proposal")
                        .WithMany("Properties")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ItMarathon.Dal.Entities.Request", "Request")
                        .WithMany("Properties")
                        .HasForeignKey("RequestId");

                    b.Navigation("PredefinedValue");

                    b.Navigation("PropertyDefinition");

                    b.Navigation("Proposal");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyValue", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.PropertyValue", "ParentPropertyValue")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItMarathon.Dal.Entities.PropertyDefinition", "PropertyDefinition")
                        .WithMany("PropertyValues")
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentPropertyValue");

                    b.Navigation("PropertyDefinition");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Proposal", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.AppUser", "AppUser")
                        .WithMany("Proposals")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.ProposalPhoto", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.Proposal", "Proposal")
                        .WithMany("Photos")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Request", b =>
                {
                    b.HasOne("ItMarathon.Dal.Entities.AppUser", "AppUser")
                        .WithMany("Requests")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.AppUser", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("Proposals");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyDefinition", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("PropertyValues");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.PropertyValue", b =>
                {
                    b.Navigation("Property");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Proposal", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ItMarathon.Dal.Entities.Request", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
